apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rtm-topology-api-ingress
  labels:
  {{- include "rtm-topology-api.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: rtm-topology-api
                port:
                  number: {{ .Values.service.port }}
