apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtm-topology-api.name" . }}
  labels:
    {{- include "rtm-topology-api.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "rtm-topology-api.selectorLabels" . | nindent 4 }}
